name: 'Deploy Windows files'

description: 'This action deploys files to a windows machine.'

inputs:
  server:
    description: 'The name of the target server'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  source-zip-file-path:
    description: 'The path to the zip file that contains the application files'
    required: true
  deployment-folder-path:
    description: 'The path to deploy the application files to'
    required: true
  clean-deployment-folder:
    description: 'Remove files that are not in the source zip file, accepts values of true or false'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String '${{ inputs.service-account-password }}' -AsPlainText -Force
        $clean_target = '${{ inputs.clean-deployment-folder }}'.ToLower() -eq 'true'
        ${{ github.action_path }}/deploy_windows_files.ps1 `
          -server '${{ inputs.server }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password `
          -source_zip_file_path '${{ inputs.source-zip-file-path }}' `
          -deployment_folder_path '${{ inputs.deployment-folder-path }}' `
          -clean_deployment_folder  $clean_target
